--CREACIÓN DE USUARIOS

CREATE USER DUENO_TABLAS
IDENTIFIED BY "Due_Tablas_2021"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

/
CREATE USER DESARROLLADOR_1
IDENTIFIED BY "Desa_Uno_2021"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

/
CREATE USER DESARROLLADOR_2
IDENTIFIED BY "Desa_Dos_2021"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;
