-- DUEÑO DE TABLAS
GRANT
    CREATE SESSION
TO dueno_tablas;

GRANT
    CREATE TABLE,
    INSERT ANY TABLE,
    UPDATE ANY TABLE,
    DELETE ANY TABLE,
    CREATE SEQUENCE,
    CREATE PUBLIC SYNONYM,
    DROP PUBLIC SYNONYM,
    CREATE INDEXTYPE,
    CREATE ANY INDEX,
    CREATE ANY PROCEDURE,
    DROP ANY PROCEDURE,
    EXECUTE ANY PROCEDURE
TO dueno_tablas;
/
-- DESARROLLADOR 1
GRANT
    CREATE SESSION
TO desarrollador_1;

GRANT
    CREATE PROCEDURE,
    CREATE TRIGGER,
    CREATE VIEW,
    CREATE MATERIALIZED VIEW
TO desarrollador_1;
/
-- DESARROLLADOR 2
GRANT
    CREATE SESSION
TO desarrollador_2;

GRANT
    CREATE PROCEDURE,
    CREATE TRIGGER,
    CREATE SEQUENCE,
    CREATE VIEW,
    CREATE MATERIALIZED VIEW
TO desarrollador_2;
/